# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='cron_kind',
            field=models.CharField(choices=[('simple', 'Simple'), ('advanced', 'Advanced')], default='simple', max_length=100),
        ),
        migrations.AddField(
            model_name='check',
            name='cron_schedule',
            field=models.CharField(default='* * * * *', max_length=100),
        ),
    ]
